### ISSUE TITLE
Dockerize and create autodeployment with Travis

### ISSUE THREAD

**Issue by mindey** [wefindx/infty2.0#21]
So, right now, the Django application is initiated with cookiecutter django, namely:

Mindey, [24.09.17 12:17]
The project was generated with cookiecutter-django, with these defaults:
```
➜  ~ cookiecutter https://github.com/pydanny/cookiecutter-django
You've cloned /Users/apple/.cookiecutters/cookiecutter-django before. Is it okay to delete and re-clone it? [yes]: yes
project_name [Project Name]: Infty
project_slug [infty]:
domain_name [example.com]: infty.xyz
version [0.1.0]:
timezone [UTC]:
use_whitenoise [y]: n
use_celery [n]: y
use_mailhog [n]: y
use_sentry_for_error_reporting [y]: y
use_opbeat [n]: n
use_pycharm [n]: n
windows [n]: n
use_docker [n]: y
use_heroku [n]: n
use_elasticbeanstalk_experimental [n]: n
use_compressor [n]: n
Select postgresql_version:
1 - 9.6
2 - 9.5
3 - 9.4
4 - 9.3
5 - 9.2
Choose from 1, 2, 3, 4, 5 [1]: 1
Select js_task_runner:
1 - Gulp
2 - Grunt
3 - None
Choose from 1, 2, 3 [1]: 3
use_lets_encrypt [n]: n
custom_bootstrap_compilation [n]: n
Select open_source_license:
1 - MIT
2 - BSD
3 - GPLv3
4 - Apache Software License 2.0
5 - Not open source
Choose from 1, 2, 3, 4, 5 [1]: 3
```

While docker development settings are generated by default ( and can be referred to at https://cookiecutter-django.readthedocs.io/en/latest/developing-locally-docker.html ), what needs to be done, is to create deployments using Travis for testing and deployment, possibly new version of docker (e.g., docker 3), and with clear separation of staging, production, and development environments, so that we could in the future conveniently develop it as an open source project, and later scale it (e.g., running docker container on Kubernetes, and distributing service across the world).

**Comment by Atorich** [comment]
Due the task is done, so we can close this issue, isn't? :)

**Comment by mindey** [comment]
@Atorich Yes~! 😊
